const TWO = [
    "Some people say that students should do volunteer work at school. What do you think about that?",
    "Some people say that children should not use smartphones until they are teenagers. What do you think about that? ",
    "Some people say that schools should start later in the morning. What do you think about that?",
    "Some people say that people should exercise every day to stay healthy. What do you think about that?",
    "Some people say that watching too much TV is bad for children. What do you think about that?",
    "Some people say that students should have more homework. What do you think about that?",
    "Some people say that public transportation should be free for students. What do you think about that?",
    "Some people say that eating breakfast is very important. What do you think about that?",
    "Some people say that people should use bicycles instead of cars more often. What do you think about that?",
    "Some people say that school uniforms are unnecessary. What do you think about that?",
    "Some people say that students should stay abroad when they are young. What do you think about that?",
    "Some people say that using social media is dangerous for teenagers. What do you think about that?",
    " Some people say that people should read more books instead of watching videos. What do you think about that?",
    "Some people say that part-time jobs are good for high school students. What do you think about that?",
    "Some people say that people should save more money for the future. What do you think about that?",
    "Some people say that animals should not be kept in zoos. What do you think about that?",
    "Some people say that schools should teach more about the environment. What do you think about that?",
    "Some people say that students should be allowed to bring smartphones to school. What do you think about that?",
    "Some people say that people should spend more time with their family. What do you think about that?",
    "Some people say that learning a second language is very important. What do you think about that?",
    "Some people say that people should stop using paper and use digital devices instead. What do you think about that?",
    "Some people say that students should clean their classrooms by themselves. What do you think about that?",
    "Some people say that watching movies is a good way to leam English. What do you think about that?",
    "Some people say that people should not work too much and should rest more. What do you think about that? ",
    "Some people say that children should play outside more than play video games. What do you think about that?",
    "Some people say that schools should teach cooking skills. What do you think about that?",
    "Some people say that people should use less electricity to protect the environment. What do you think about that?",
    "Some people say that studying history is not important. What do you think about that?",
    "Some people say that people should help others more in their community. What do you think about that?",
    "Some people say that learning online is as good as learning in a classroom. What do you think about that?",
    "Some people say that students should learn how to cook at school. What do you think about that?",
    "Some people say that people should not use smartphones while walking. What do you think about that?",
    "Some people say that students should study more science and technology. What do you think about that?",
    "Some people say that people should travel more to understand other cultures. What do you think about that?",
    "Some people say that children should help with housework at home. What do you think about that?",
    "Some people say that people should not eat too much sugar. What do you think about that?",
    "Some people say that schools should have more English classes. What do you think about that?",
    "Some people say that people should read newspapers every day. What do you think about that?",
    "Some people say that students should not use calculators in math class. What do you think about that?",
    "Some people say that people should try to live an eco-friendly life. What do you think about that?",
    "Some people say that students should join school clubs. What do you think about that?",
    "Some people say that people should sleep at least eight hours a day. What do you think about that?",
    "Some people say that children should learn how to manage money. What do you think about that?",
    "Some people say that people should not depend too much on the internet. What do you think about that?",
    "Some people say that students should learn how to give presentations. What do you think about that?",
    "Some people say that people should try new things even if they fail. What do you think about that?",
    "Some people say that people should eat local food more often. What do you think about that?",
    "Some people say that schools should teach first aid. What do you think about that?",
    "Some people say that people should talk more with older people. What do you think about that?",
    "Some people say that students should think more about their future goals. What do you think about that?"
]



const P2PLUS = [

]


const P2 = [
    "Do you think using smartphones at school is a good idea?",
    "Do you think students should wear school uniforms?",
    "Do you think people should use bicycles more than cars?",
    "Do you think we should have more holidays?",
    "Do you think it is important to recycle?",
    "Do you think students should do volunteer work?",
    "Do you think having pets is good for children?",
    "Do you think it is better to live in a city than in the countryside?",
    "Do you think watching TV is a good way to learn?",
    "Do you think children should help with housework?",
    "Do you think using the Internet every day is good?",
    "Do you think video games are good for children?",
    "Do you think social media is useful?",
    "Do you think robots will be important in the future?",
    "Do you think people should read books instead of watching videos?",
    "Do you think AI will help students in the future?",
    "Do you think students should use tablets in class?",
    "Do you think we use too many electronic devices?",
    "Do you think listening to music while studying is a good idea?",
    "Do you think smartphones are too expensive?",
    "Do you think we should plant more trees in cities?",
    "Do you think people should use less plastic?",
    "Do you think schools should teach more about the environment?",
    "Do you think zoos are good for animals?",
    "Do you think it’s important to save water?",
    "Do you think people should clean up parks more often?",
    "Do you think global warming is a big problem?",
    "Do you think we should protect wild animals?",
    "Do you think people should use public transportation more?",
    "Do you think nature is important for people’s health?",
    "Do you think school lunch is important?",
    "Do you think students should have more free time?",
    "Do you think studying English is important?",
    "Do you think schools should have more school events?",
    "Do you think students should study during summer vacation?",
    "Do you think school rules are too strict?",
    "Do you think it is important to learn a second foreign language?",
    "Do you think students should choose their own subjects?",
    "Do you think students should bring their own lunch?",
    "Do you think studying with friends is better than studying alone?",
    "Do you often go shopping with your family?",
    "Do you usually help your parents at home?",
    "Do you like cooking?",
    "Do you often go to the park on weekends?",
    "Do you usually eat breakfast at home?",
    "Do you have a part-time job?",
    "Do you prefer spending time indoors or outdoors?",
    "Do you use a bicycle to go to school?",
    "Do you play sports?",
    "Do you enjoy watching movies with your family?",
    "Do you enjoy studying English at school?",
    "Do you often use a computer at school?",
    "Do you think English is important for your future?",
    "Do you want to study abroad in the future?",
    "Do you prefer group study or studying alone?",
    "Do you often do homework?",
    "Do you play school events like sports day?",
    "Do you usually talk with friends during lunch break?",
    "Do you like to go dancing?",
    "Do you play musical instruments?",
    "Do you like painting pictures?",
    "Do you prefer reading books in your free time?",
    "Do you play video games?",
    "Do you like listening to music?",
    "Do you prefer to study in the morning or at night?",
    "Do you enjoy traveling to new places?",
    "Do you prefer watching TV or reading books?",
    "Do you watch YouTube every day?",
    "Do you want to be a teacher in the future?",
    "Do you want to be a scientist in the future?",
    "Do you want to be a doctor in the future?",
    "Do you want to be a singer in the future?",
    "Do you want to be a soccer player in the future?",
    "Do you want to be a nurse in the future?",
    "Do you want to be a farmer or business person in the future?",
    "Do you want to be a volunteer worker?",
    "Do you want to live in a big city in the future?",
    "Do you want to live in the countryside in the future?",
    "Do you want to study overseas?",
    "Do you want to have a pet when you grow up?"
]

const THREE = [
    "How do you usually go to the convenience store near your house?",
    "How many hours do you study every day?",
    "How many people do you have in your family?",
    "How many times have you been on a plane?",
    "What are you going to do after this test?",
    "What are you planning to do this spring (winter, summer)?",
    "What city would you like to visit in the future?",
    "What country do you want to go to?",
    "What did you do during your summer vacation?",
    "What did you do last night?",
    "What did you do yesterday?",
    "What did you eat this morning?",
    "What do you do to help your family?",
    "What do you enjoy on your holidays?",
    "What do you like to do on your vacation?",
    "What time do you usually eat dinner?",
    "Where are you going to go after this interview?",
    "Where do you often go in your free time?",
    "Where do you often go on Sundays?",
    "Where do you like to go with your family?",
    "Where do you want to visit in the future?",
    "Where would you like to go on weekends?",
    "Which do you like better, summer or winter!",
    "Which do you like better, TV or the Internet?",
    "Which do you like to go to, the mountains or the beaches?",
    "Are you a student from any school?<br>Yes.-> Please tell me more.<br>No. -> What do you like to do when you are at home?",
    "Are you good at playing music?<br>Yes.-> Please tell me more.<br>No.-> What are you good at?"
]

const PICK = [THREE, P2, P2PLUS, TWO];